URL_SERVICE = "https://cnt-c30302b7-db40-446d-8f5b-1c371efcf315.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCT_KITS_PATH = "/api/v1/products/kits/"